### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by gsacre** [Techmentis/flinkiso-lite#1]
Hi,

We are trying to evaluate the Lite version of flinkiso but I can't install it.

Basically I get on the "index.php" file, I click on "Start installation", and then I get a blank page (install.php).
When I have a look at "install.php", I see that there are a few name renaming but that's it.

Could you please fix the installation process?

Thanks!

**Comment by Techmentis** [comment]
Hi,
Please visit system requirements page here : http://www.flinkiso.com/help/system-requirments.html
and make sure you meet these requirements. Many of the times, its either permission issues or mod_write issue. You can also check your httpd.conf file and see if the following settings exists. 
<Directory />
    Options Indexes FollowSymLinks
    AllowOverride All  
</Directory>

Let us know if this helps.

**Comment by gsacre** [comment]
Thanks!

That did the trick:

Options Indexes FollowSymLinks
AllowOverride All
