### ISSUE TITLE
Trying to 'Act' on a registered CAPA

### ISSUE THREAD

**Issue by gsacre** [Techmentis/flinkiso-lite#3]
When I try to click on the 'Act' button from a registered CAPA, I get the following error message:

 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ChangeAdditionDeletionRequest.proposed_changes' in 'field list'

**Comment by Techmentis** [comment]
Hi gsacre, 
Can you try removing following from app/Model/ChangeAdditionDeletionRequest.php file and try again ?

proposed_changes' => array(
            'notempty' => array(
                'rule' => array('notempty'),
            ),
        ),

**Comment by gsacre** [comment]
Sorry, it didn't do the trick, I still have the same message.
Doing a "grep" on "proposed_changes", it appears to be deep in the logic of the code as in the controller for "ChangeAdditionDeletionRequests".
Should we also clear the code there? (there are quite some numerous entries...)

**Comment by Techmentis** [comment]
Hi Gsacre, 

Please try renaming "proposed_document_changes" field to "proposed_changes" in change_addition_deletion_requests table. This should resolve the issue. Also make sure you clear all files under cache folder  in app/tmp/ directory.

**Comment by gsacre** [comment]
It worked.
Thanks!
