### ISSUE TITLE
flinkiso is not open source

### ISSUE THREAD

**Issue by ghost** [Techmentis/flinkiso-lite#5]
flinkiso is not open source

**Comment by Techmentis** [comment]
How it is not open source, can you explain?

**Comment by ghost** [comment]
it does not basic functionality without licence and is limited
can we use without licence file?
or can we use primary functionality like audit management (or capa)
can we customize that?
 thanks Techmentis

**Comment by Techmentis** [comment]
There are two versions of the application. 1. Free Open Source (which is available here for download) and 2. Commercial Edition (open source but not free). In both cases, you get the entire code of the respective versions, which you can customize and use (you can not resell / re-brand etc). In case of commercial edition, license fee is involved and we provide support & maintenance. 

Regards

**Comment by ghost** [comment]
# comparison between your free and original edition:

when we install 1.free source version only base info are available for data entry!
other important functionlaitys for QMS is not avaliable:
two below links are comparison between your free and original edition:

![installed flinkiso](https://user-images.githubusercontent.com/34779731/34905883-4883259c-f877-11e7-8296-fabe4a55519a.jpg)

![orginal flinkiso](https://user-images.githubusercontent.com/34779731/34905878-29c6ee40-f877-11e7-9e81-7d43ef4d2adf.jpg)

## is it true?

**Comment by Techmentis** [comment]
You are right. We have two versions of the application as explained earlier. Its is not in our organisation's interest to provide latest commercial version for free. However both versions are Open Source. That means, when you purchase the license, you get access to unrestricted source code. It seems you are confusing Open Source with Free.
